import html
import os
import zipfile
from datetime import datetime


OUT_PATH = os.path.abspath("Student_Verification_Teammate_Presentation_Guide.docx")


def esc(text):
    return html.escape(str(text), quote=False)


def run(text, bold=False, italic=False):
    props = []
    if bold:
        props.append("<w:b/>")
    if italic:
        props.append("<w:i/>")
    rpr = f"<w:rPr>{''.join(props)}</w:rPr>" if props else ""
    return f"<w:r>{rpr}<w:t xml:space=\"preserve\">{esc(text)}</w:t></w:r>"


def para(text="", style=None, bold=False, italic=False):
    ppr = f"<w:pPr><w:pStyle w:val=\"{style}\"/></w:pPr>" if style else ""
    return f"<w:p>{ppr}{run(text, bold=bold, italic=italic)}</w:p>"


def mixed_para(parts, style=None):
    ppr = f"<w:pPr><w:pStyle w:val=\"{style}\"/></w:pPr>" if style else ""
    body = "".join(run(text, bold=bold, italic=italic) for text, bold, italic in parts)
    return f"<w:p>{ppr}{body}</w:p>"


def bullet(text):
    return f"""
    <w:p>
      <w:pPr>
        <w:numPr><w:ilvl w:val="0"/><w:numId w:val="1"/></w:numPr>
      </w:pPr>
      {run(text)}
    </w:p>
    """


def numbered(text):
    return f"""
    <w:p>
      <w:pPr>
        <w:numPr><w:ilvl w:val="0"/><w:numId w:val="2"/></w:numPr>
      </w:pPr>
      {run(text)}
    </w:p>
    """


def table(rows, widths=None):
    if widths is None:
        widths = [3000] * len(rows[0])
    grid = "".join(f"<w:gridCol w:w=\"{w}\"/>" for w in widths)
    out = [
        "<w:tbl>",
        "<w:tblPr><w:tblW w:w=\"9360\" w:type=\"dxa\"/><w:tblInd w:w=\"120\" w:type=\"dxa\"/>",
        "<w:tblBorders><w:top w:val=\"single\" w:sz=\"4\" w:color=\"D9E2EA\"/><w:left w:val=\"single\" w:sz=\"4\" w:color=\"D9E2EA\"/><w:bottom w:val=\"single\" w:sz=\"4\" w:color=\"D9E2EA\"/><w:right w:val=\"single\" w:sz=\"4\" w:color=\"D9E2EA\"/><w:insideH w:val=\"single\" w:sz=\"4\" w:color=\"D9E2EA\"/><w:insideV w:val=\"single\" w:sz=\"4\" w:color=\"D9E2EA\"/></w:tblBorders>",
        "<w:tblCellMar><w:top w:w=\"100\" w:type=\"dxa\"/><w:left w:w=\"120\" w:type=\"dxa\"/><w:bottom w:w=\"100\" w:type=\"dxa\"/><w:right w:w=\"120\" w:type=\"dxa\"/></w:tblCellMar>",
        "</w:tblPr>",
        f"<w:tblGrid>{grid}</w:tblGrid>",
    ]
    for r, row in enumerate(rows):
        out.append("<w:tr>")
        for i, cell in enumerate(row):
            fill = "<w:shd w:fill=\"E8EEF5\"/>" if r == 0 else ""
            out.append(
                f"<w:tc><w:tcPr><w:tcW w:w=\"{widths[i]}\" w:type=\"dxa\"/>{fill}</w:tcPr>"
                f"{para(cell, bold=(r == 0))}</w:tc>"
            )
        out.append("</w:tr>")
    out.append("</w:tbl>")
    return "\n".join(out)


def page_break():
    return '<w:p><w:r><w:br w:type="page"/></w:r></w:p>'


body = []

body.append(para("Student Verification System", "Title"))
body.append(para("Teammate Frontend, System, Demo, and Presentation Preparation Guide", "Subtitle"))
body.append(para(f"Prepared for hackathon presentation | Updated {datetime.now().strftime('%Y-%m-%d')}"))
body.append(para("Use this guide to understand the project, explain the frontend confidently, run the demo, and answer judge questions without needing to know every line of code.", "Callout"))

body.append(para("1. The project in one minute", "Heading1"))
body.append(mixed_para([
    ("Problem: ", True, False),
    ("Schools manually enter Class 11/12 registration details. Small mistakes in names, DOB, SEE symbol number, address, or parent details can create board/certificate problems later.", False, False),
]))
body.append(mixed_para([
    ("Solution: ", True, False),
    ("The system checks school-submitted registration data against SEE/Class 10 master records before final board dispatch. Correct records go directly to board dispatch. Wrong records become flagged cases, students receive secure correction links, and school admins re-verify before final submission.", False, False),
]))
body.append(mixed_para([
    ("Core value: ", True, False),
    ("It is not just a form. It is an end-to-end verification workflow with audit trail, correction portal, proof upload, and board dispatch simulation.", False, False),
]))

body.append(para("2. What your teammate must remember", "Heading1"))
for item in [
    "This is a web-based government-style portal, not a mobile app.",
    "There are two main users in this prototype: school admin and student correction link user.",
    "Students do not log in. They open a secure ticket link generated by the system.",
    "The board/NEB dashboard is simulated through Board Dispatch, not fully implemented as a separate user dashboard.",
    "The strongest demo story is: submit -> verify -> flag -> student correction -> admin review -> board dispatch -> audit trail.",
]:
    body.append(bullet(item))

body.append(para("3. Frontend architecture analysis", "Heading1"))
body.append(table([
    ["Frontend area", "What it does", "What to say to judges"],
    ["App routing", "App.jsx decides whether to show Student Portal, Login, or Admin Dashboard based on URL and admin token.", "The frontend keeps student and admin flows separate without needing a complex router."],
    ["Login screen", "School admin signs in with demo credentials stored as a token in localStorage.", "For prototype we use demo auth; production would use official school accounts and role-based login."],
    ["Admin Dashboard", "Main portal with Dashboard, Registration Entry, Flagged Cases, Board Dispatch, and Audit Trail sections.", "The admin does not jump through random screens; each government workflow has a separate section."],
    ["Student Portal", "Opened through /student/ticket/:ticketId?token=... and shows only flagged fields plus correction form.", "Students can correct mistakes without creating accounts, using SMS-secure links."],
    ["UI polish", "Status badges, official empty states, loading indicators, submission receipt animation, grouped forms, copy SMS link.", "The interface is designed to feel deployable, not toy-like."],
], [1800, 3900, 3660]))

body.append(para("4. Frontend screens and what each screen proves", "Heading1"))
body.append(para("Login Screen", "Heading2"))
for item in [
    "Shows this is not a public open form; school admin access is required.",
    "Demo credentials: username admin, password admin123.",
    "In production this becomes official school account login, not hard-coded demo login.",
]:
    body.append(bullet(item))

body.append(para("Dashboard", "Heading2"))
for item in [
    "Shows master SEE records count, total submissions, approved records, active flags, pending admin reviews, and records sent to board.",
    "Use it at the start to prove this is a monitoring console.",
    "After actions, return here to show numbers changed.",
]:
    body.append(bullet(item))

body.append(para("Registration Entry", "Heading2"))
for item in [
    "Single student form starts empty like a real data-entry screen.",
    "Fields are grouped into identifiers, name details, parent details, birth details, institution/address.",
    "Admin can submit one record or upload a CSV for bulk verification.",
    "After submit/upload, the page stays in place and shows an official acknowledgement with approved/flagged counts.",
]:
    body.append(bullet(item))

body.append(para("Flagged Cases", "Heading2"))
for item in [
    "Shows each flagged case with status badge: Waiting Student, Pending Admin, Board Review, or Resolved.",
    "Mismatch table shows field-by-field difference: school entry vs official record, rule, and severity.",
    "Admin can copy the SMS correction link and open the student portal.",
    "If student does not respond, admin can still verify documents offline and resolve the case.",
]:
    body.append(bullet(item))

body.append(para("Student Correction Portal", "Heading2"))
for item in [
    "Student opens secure link with ticket token; no login needed.",
    "Student sees flagged details, enters corrected information, adds description, and uploads proof PDF/JPG/PNG.",
    "The ticket has expiry to reduce link misuse.",
]:
    body.append(bullet(item))

body.append(para("Board Dispatch", "Heading2"))
for item in [
    "Shows records that passed verification and were sent to final board dispatch.",
    "Each dispatch has a source and SHA-256 payload hash preview.",
    "Explain this as a prototype integration point for NEB/IEMIS.",
]:
    body.append(bullet(item))

body.append(para("Audit Trail", "Heading2"))
for item in [
    "Shows login, flagged case creation, SMS link generation, student correction, admin resolution, and board dispatch events.",
    "This is important for government accountability and traceability.",
]:
    body.append(bullet(item))

body.append(page_break())

body.append(para("5. Backend mechanism explained simply", "Heading1"))
body.append(table([
    ["Step", "Backend action", "Result"],
    ["1. Admin submits", "POST /submissions or /submissions/bulk receives form/CSV data.", "Record enters verification engine."],
    ["2. Normalize", "Backend ensures all expected fields exist: student_id, SEE symbol, English/Nepali name, parent names, DOB, gender, school code, address.", "Consistent comparison input."],
    ["3. Find master", "System finds SEE/Class 10 master record by student_id or see_symbol_no.", "If no match, record is flagged."],
    ["4. Compare fields", "compare.js checks strict and fuzzy fields.", "Exact matches are approved; differences become flagged fields."],
    ["5. Approved path", "Backend locks record and creates board dispatch payload with SHA-256 hash.", "Record appears in Board Dispatch."],
    ["6. Flagged path", "Backend creates ticket ID, secure token, expiry, SMS text, and verification case.", "Record appears in Flagged Cases."],
    ["7. Student correction", "Student submits correction plus proof file through secure ticket endpoint.", "Case becomes Pending Admin."],
    ["8. Admin resolves", "Admin submits final record for re-verification.", "Resolved case is dispatched to board."],
], [1250, 4550, 3560]))

body.append(para("6. Verification rules", "Heading1"))
body.append(table([
    ["Field type", "Fields", "Rule", "Why"],
    ["Strict", "SEE symbol number, DOB B.S., DOB A.D., gender, school code", "Must match exactly", "These identifiers should not vary. A small difference can identify a different record."],
    ["Fuzzy review", "English name, Nepali name, father name, mother name, permanent address", "Allows near match but still flags for review", "Names/address can have spelling variations, but must be reviewed before final approval."],
], [1500, 3300, 2100, 2460]))

body.append(para("7. Demo flow for stage presentation", "Heading1"))
for step in [
    "Open frontend: http://127.0.0.1:5173",
    "Login with admin / admin123.",
    "Show Dashboard and explain metrics.",
    "Open Registration Entry and explain single entry plus bulk upload.",
    "Submit a verified record or upload sample CSV. Show submission acknowledgement and approved/flagged counts.",
    "Open Board Dispatch to show auto-approved records and payload hash.",
    "Open Flagged Cases to show mismatch details and correction link.",
    "Copy correction link and open it in a browser tab.",
    "Submit student correction with description and proof file.",
    "Return to Flagged Cases, show proof received, then re-verify and send to board.",
    "Open Audit Trail and close with accountability story.",
]:
    body.append(numbered(step))

body.append(para("8. Speaking script your teammate can memorize", "Heading1"))
body.append(para("Opening, 20 seconds", "Heading2"))
body.append(para("Good morning. Our project is a Student Record Verification System for Class 11/12 registration. The problem is that schools often submit student data manually, and small mistakes in names, DOB, SEE symbol number, address, or parent details can create certificate and board registration problems later. Our system verifies the data before final board dispatch."))
body.append(para("While showing Registration Entry", "Heading2"))
body.append(para("Here, the school admin can enter a single student or upload a bulk CSV. The form is grouped like an official portal: identifiers, name details, parent details, birth details, and institution/address. When submitted, the backend immediately compares the data with SEE master records."))
body.append(para("While showing flagged case", "Heading2"))
body.append(para("This record has a mismatch. The system does not silently accept it. It creates a flagged case, shows exactly which field is different, and generates a secure correction link that can be sent to the student by SMS."))
body.append(para("While showing student portal", "Heading2"))
body.append(para("The student does not need a full login. They open the secure link, review the flagged fields, enter the corrected information, explain the issue, and upload proof such as citizenship, birth certificate, or SEE certificate."))
body.append(para("While showing board dispatch", "Heading2"))
body.append(para("Once the record is verified, it is dispatched to the board. We also generate a payload hash, which shows how this can become tamper-evident in a real NEB/IEMIS integration."))
body.append(para("Closing, 15 seconds", "Heading2"))
body.append(para("So the main value is prevention. Instead of discovering mistakes after certificates are printed, this system catches them before board submission, creates a correction workflow, and keeps an audit trail for accountability."))

body.append(page_break())

body.append(para("9. Q&A preparation", "Heading1"))
body.append(table([
    ["Judge question", "Strong answer"],
    ["Is this only a form?", "No. The form is only the entry point. The system includes verification rules, flagged case management, secure student correction links, proof upload, admin re-verification, board dispatch, and audit trail."],
    ["Why does the student not log in?", "For speed and accessibility. Students receive a secure tokenized link, similar to an SMS correction link. It expires, and production can add OTP if required."],
    ["How do you know the data is true?", "The prototype compares against SEE/Class 10 master records and requires proof upload for corrections. In production, this would connect to official NEB/IEMIS/SEE databases and school accounts."],
    ["What happens if the student does not respond?", "The school admin can still review offline documents and correct the flagged case from the admin dashboard. This prevents workflow blockage."],
    ["What is strict vs fuzzy checking?", "Strict fields like SEE symbol number and DOB must match exactly. Fuzzy fields like names and address can have spelling differences, so they are flagged for human review."],
    ["Is SMS actually sent?", "In this prototype, SMS is simulated by generating the correction message and link. The integration point is ready; production would connect an SMS gateway."],
    ["Why SQLite?", "SQLite is lightweight and good for hackathon persistence. For production, we would use PostgreSQL or a government-managed database."],
    ["How is proof stored?", "Proof files are uploaded to the backend uploads folder with file type and size validation. Production should use secure object storage with access control."],
    ["How does board dispatch work?", "Approved payloads are saved with dispatch ID, source, status, and SHA-256 hash. This simulates final NEB/IEMIS submission and tamper-evident payload tracking."],
    ["What are the limitations?", "Demo auth, simulated SMS, simulated board integration, local file storage, and prototype database. The workflow is real; production integrations would replace demo parts."],
], [2500, 6860]))

body.append(para("10. Common terms your teammate should know", "Heading1"))
body.append(table([
    ["Term", "Meaning"],
    ["SEE master record", "The official Class 10/SEE record used as trusted reference data."],
    ["Flagged case", "A submitted record that has at least one mismatch requiring correction or review."],
    ["Ticket", "A secure correction case with ticket ID and tokenized student link."],
    ["Board dispatch", "Final approved data marked as sent to NEB/IEMIS in the prototype."],
    ["Payload hash", "SHA-256 fingerprint of approved data, useful for tamper-evidence."],
    ["Audit trail", "Permanent log of important system actions and who/what performed them."],
], [2200, 7160]))

body.append(para("11. Frontend code map", "Heading1"))
body.append(table([
    ["File/component", "Responsibility"],
    ["frontend/src/App.jsx", "Main React app. Contains LoginScreen, AdminDashboard, StudentPortal, CaseReview, RecordFields, tables, status badges, receipt, and processing indicator."],
    ["frontend/src/App.css", "Government portal styling: layout, navigation, forms, case queue, badges, receipt animation, responsive behavior."],
    ["frontend/src/utils.js", "Small helpers for API errors, student ticket URL parsing, dates, audit action formatting."],
    ["sample-student-bulk-upload.csv", "Ready CSV with 20 students for bulk upload demo."],
], [2400, 6960]))

body.append(para("12. Presentation rehearsal checklist", "Heading1"))
for item in [
    "Can explain the problem in 20 seconds.",
    "Can login and name every main tab.",
    "Can explain why the form has Nepali name and permanent address.",
    "Can submit a record and explain approved vs flagged result.",
    "Can show mismatch table and explain school entry vs official record.",
    "Can copy/open student correction link.",
    "Can explain proof upload and admin re-verification.",
    "Can explain board dispatch and payload hash.",
    "Can answer what is prototype vs production.",
    "Can recover demo using Reset Workspace.",
]:
    body.append(bullet(item))

body.append(para("13. Backup plan if demo fails", "Heading1"))
for step in [
    "Do not panic. Say: We have a reset option because this is a workflow demo with persistent data.",
    "Click Reset Workspace in the header.",
    "Restart backend: cd backend, npm start.",
    "Restart frontend: cd frontend, npm run dev.",
    "Use the CSV file sample-student-bulk-upload.csv if single entry is slow.",
    "If student link is hard to open, explain the flow from Flagged Cases using the SMS text and mismatch table.",
]:
    body.append(numbered(step))

body.append(para("14. Final advice for teammate", "Heading1"))
body.append(para("Speak like you understand the workflow, not like you memorized code. Judges care about problem clarity, realistic flow, and what can be productionized. Keep saying: verify before dispatch, student correction link, proof upload, admin re-verification, audit trail. Those five phrases carry the project."))


document_xml = f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    {''.join(body)}
    <w:sectPr>
      <w:pgSz w:w="12240" w:h="15840"/>
      <w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="708" w:footer="708" w:gutter="0"/>
    </w:sectPr>
  </w:body>
</w:document>
"""

styles_xml = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:style w:type="paragraph" w:default="1" w:styleId="Normal">
    <w:name w:val="Normal"/>
    <w:pPr><w:spacing w:after="120" w:line="300" w:lineRule="auto"/></w:pPr>
    <w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:sz w:val="22"/><w:color w:val="1F2933"/></w:rPr>
  </w:style>
  <w:style w:type="paragraph" w:styleId="Title">
    <w:name w:val="Title"/>
    <w:pPr><w:spacing w:after="120"/></w:pPr>
    <w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:b/><w:sz w:val="52"/><w:color w:val="0F3F38"/></w:rPr>
  </w:style>
  <w:style w:type="paragraph" w:styleId="Subtitle">
    <w:name w:val="Subtitle"/>
    <w:pPr><w:spacing w:after="180"/></w:pPr>
    <w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:sz w:val="26"/><w:color w:val="4B5F58"/></w:rPr>
  </w:style>
  <w:style w:type="paragraph" w:styleId="Heading1">
    <w:name w:val="heading 1"/><w:basedOn w:val="Normal"/><w:next w:val="Normal"/>
    <w:pPr><w:keepNext/><w:spacing w:before="360" w:after="200"/><w:outlineLvl w:val="0"/></w:pPr>
    <w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:b/><w:sz w:val="32"/><w:color w:val="2E74B5"/></w:rPr>
  </w:style>
  <w:style w:type="paragraph" w:styleId="Heading2">
    <w:name w:val="heading 2"/><w:basedOn w:val="Normal"/><w:next w:val="Normal"/>
    <w:pPr><w:keepNext/><w:spacing w:before="280" w:after="140"/><w:outlineLvl w:val="1"/></w:pPr>
    <w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:b/><w:sz w:val="26"/><w:color w:val="2E74B5"/></w:rPr>
  </w:style>
  <w:style w:type="paragraph" w:styleId="Callout">
    <w:name w:val="Callout"/>
    <w:pPr><w:spacing w:before="120" w:after="160"/><w:shd w:fill="EEF7F3"/></w:pPr>
    <w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:sz w:val="23"/><w:color w:val="1F4D44"/></w:rPr>
  </w:style>
</w:styles>
"""

numbering_xml = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:numbering xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:abstractNum w:abstractNumId="1">
    <w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="bullet"/><w:lvlText w:val="•"/><w:pPr><w:ind w:left="540" w:hanging="270"/></w:pPr></w:lvl>
  </w:abstractNum>
  <w:num w:numId="1"><w:abstractNumId w:val="1"/></w:num>
  <w:abstractNum w:abstractNumId="2">
    <w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/><w:pPr><w:ind w:left="540" w:hanging="270"/></w:pPr></w:lvl>
  </w:abstractNum>
  <w:num w:numId="2"><w:abstractNumId w:val="2"/></w:num>
</w:numbering>
"""

content_types = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
  <Override PartName="/word/numbering.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml"/>
  <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
  <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
</Types>
"""

rels = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>
"""

document_rels = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering" Target="numbering.xml"/>
</Relationships>
"""

core = f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <dc:title>Student Verification Teammate Presentation Guide</dc:title>
  <dc:creator>Codex</dc:creator>
  <cp:lastModifiedBy>Codex</cp:lastModifiedBy>
  <dcterms:created xsi:type="dcterms:W3CDTF">{datetime.utcnow().isoformat()}Z</dcterms:created>
  <dcterms:modified xsi:type="dcterms:W3CDTF">{datetime.utcnow().isoformat()}Z</dcterms:modified>
</cp:coreProperties>
"""

app = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">
  <Application>Codex</Application>
</Properties>
"""

with zipfile.ZipFile(OUT_PATH, "w", zipfile.ZIP_DEFLATED) as z:
    z.writestr("[Content_Types].xml", content_types)
    z.writestr("_rels/.rels", rels)
    z.writestr("word/document.xml", document_xml)
    z.writestr("word/_rels/document.xml.rels", document_rels)
    z.writestr("word/styles.xml", styles_xml)
    z.writestr("word/numbering.xml", numbering_xml)
    z.writestr("docProps/core.xml", core)
    z.writestr("docProps/app.xml", app)

print(OUT_PATH)
